import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import "./globals.css";
import { AppSidebar } from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <SidebarProvider className="">
          <AppSidebar />
          <main className="w-full bg-[#282828]">
            <div className="w-full flex justify-between items-center h-10 px-3">
              <SidebarTrigger className="text-white" />
            </div>
            <div className="md:w-10/12 md:m-auto w-full text-gray-200 px-2 md:px-0">
              {children}
            </div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
